model_name_or_path: unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit

stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,k_proj,v_proj
lora_rank: 16

dataset: lmsys
dataset_dir: data
template: llama3
cutoff_len: 2720
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: saves/lmsys/llama3.1-8B_lora_sft
logging_steps: 10
save_steps: 1800
plot_loss: true
overwrite_output_dir: true

use_unsloth: True
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
