### model
model_name_or_path: unsloth/llama-3-8b-Instruct-bnb-4bit

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,k_proj,v_proj
lora_rank: 16

### dataset
dataset: lmsys_ultrafeedback_aug
dataset_dir: data
template: llama3
cutoff_len: 2720
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/lmsys_ultrafeedback_aug/llama3-8B/lora_sft
logging_steps: 10
save_steps: 1800
plot_loss: true
overwrite_output_dir: true

### train
use_unsloth: True
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
